[build]
  publish = "exampleSite/public"
  command = "npx tinacms build && cd exampleSite && hugo --gc --minify --themesDir ../.."
  
[build.environment]
  HUGO_VERSION = "0.73.0"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "/"

